# Generated by Django 2.0.8 on 2018-09-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eth_address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
