# Generated by Django 2.0.8 on 2018-09-14 08:46

from django.db import migrations
import django_eth.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eth_address',
            field=django_eth.models.EthereumAddressField(blank=True, null=True),
        ),
    ]
