<?php

namespace DashboardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CapsuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapsuleRepository extends EntityRepository
{
}
