# Generated by Django 2.0.8 on 2018-10-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='EmailMessage',
        ),
    ]
