# Generated by Django 2.0.8 on 2018-10-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20181003_1141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailMessage',
            new_name='Message',
        ),
    ]
