# Generated by Django 2.0.8 on 2018-08-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20180828_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsuscriber',
            name='unique',
            field=models.BooleanField(default=False),
        ),
    ]
