          
app_home:
    path:     /
    defaults: { _controller: AppBundle:App:home }
              
app_home_submit_email:
    path:     /submitEmail
    defaults: { _controller: AppBundle:App:submitEmail }
                  
app_home_submit_contact:
    path:     /submitContact
    defaults: { _controller: AppBundle:App:submitContact }
    
    
                   