# Generated by Django 2.0.8 on 2018-09-13 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capsules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsule',
            name='assignees',
        ),
        migrations.AddField(
            model_name='capsule',
            name='beneficiaries',
            field=models.ManyToManyField(related_name='beneficiaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
